### PR TITLE
Fixes README: Supported FPGA boards (#42)

### PR DESCRIPTION
**Pull request by pjattke**
Clarifies that both mentioned FPGA boards are supported.

### CODE REVIEW

**Comment by jedrzejboczar** [comment]
Thanks for the clarification. Now when thinking about it we should probably also mention that in the simulation no bit-filps due to row-hammer will occur. The simulation is mostly useful for testing that the command sequences we send are indeed what we wanted. Maybe in the future we could try to also simulate the row-hammer phenomenon using some heuristics, but that's not implemented now.

**Comment by jedrzejboczar** [comment]
Could you please add a note about row-hammer in simulation? It could help to avoid confusion and then we can merge it.

**Comment by pjattke** [comment]
@jedrzejboczar Sure! I added a brief explanation.

**Comment by jedrzejboczar** [comment]
Thanks, merging.

**Pull request merged**
